-- +60 предметов:20 common, 20 rare, 10 mythical, 5 legendary, 5 immortal.
insert into public.items (slug, name, slot, price, icon, rarity) values
  ('hat_cotton_cap', 'Хлопковая кепка', 'hat', 55, '🧢', 'common'),
  ('glasses_reading', 'Очки для чтения', 'glasses', 62, '🤓', 'common'),
  ('scarf_plain', 'Простой шарф', 'accessory', 68, '🧣', 'common'),
  ('ring_bronze_band', 'Бронзовое кольцо', 'ring', 72, '💍', 'common'),
  ('gloves_cloth', 'Тряпичные перчатки', 'gloves', 78, '🧤', 'common'),
  ('belt_leather_simple', 'Простой кожаный ремень', 'belt', 82, '🔗', 'common'),
  ('charm_smile_pin', 'Значок-улыбка', 'charm', 58, '😊', 'common'),
  ('mask_cloth_casual', 'Тканевая маска', 'mask', 88, '😷', 'common'),
  ('cloak_light_hood', 'Лёгкий капюшон', 'cloak', 95, '🧵', 'common'),
  ('shoulder_patch_star', 'Нашивка со звездой', 'shoulder', 52, '⭐', 'common'),
  ('socks_striped', 'Полосатые носки', 'socks', 60, '🧦', 'common'),
  ('keychain_heart', 'Брелок-сердечко', 'charm', 74, '💖', 'common'),
  ('bow_tie_red', 'Красная бабочка', 'accessory', 92, '👔', 'common'),
  ('earring_pearl', 'Жемчужная серёжка', 'earring', 66, '🦪', 'common'),
  ('hat_cap_backwards', 'Кепка задом наперёд', 'hat', 90, '🎩', 'common'),
  ('mittens_wool', 'Шерстяные варежки', 'gloves', 84, '🧤', 'common'),
  ('locket_empty', 'Медальон без фото', 'accessory', 100, '📿', 'common'),
  ('ribbon_hair', 'Лента в волосах', 'accessory', 64, '🎀', 'common'),
  ('tote_canvas', 'Сумка-шопер', 'accessory', 108, '👜', 'common'),
  ('bandana_classic', 'Классическая бандана', 'accessory', 76, '🟥', 'common'),
  ('hat_fedora_night', 'Федора ночного города', 'hat', 268, '🎭', 'rare'),
  ('glasses_steampunk', 'Стимпанк-очки', 'glasses', 292, '🥽', 'rare'),
  ('beard_braided', 'Заплетённая борода', 'beard', 276, '🧔', 'rare'),
  ('cane_silver', 'Серебряная трость', 'weapon', 340, '🦯', 'rare'),
  ('cloak_traveler', 'Плащ странника', 'cloak', 342, '🧥', 'rare'),
  ('compass_rose', 'Компас с розой ветров', 'accessory', 310, '🧭', 'rare'),
  ('mask_venetian', 'Венецианская маска', 'mask', 356, '🎭', 'rare'),
  ('ring_signet', 'Перстень с печатью', 'ring', 382, '💎', 'rare'),
  ('sword_training', 'Тренировочный меч', 'weapon', 298, '⚔️', 'rare'),
  ('gloves_engineer', 'Инженерные перчатки', 'gloves', 324, '🧤', 'rare'),
  ('pauldron_single_iron', 'Железный наплечник', 'shoulder', 360, '🛡️', 'rare'),
  ('halo_dim', 'Тусклый нимб', 'aura', 322, '🌟', 'rare'),
  ('wings_paper', 'Бумажные крылья', 'wings', 286, '📄', 'rare'),
  ('pet_rock_googly', 'Камень с глазками', 'pet', 308, '🪨', 'rare'),
  ('lantern_warm', 'Тёплый фонарь', 'accessory', 294, '🏮', 'rare'),
  ('watch_pocket', 'Карманные часы', 'accessory', 418, '⌚', 'rare'),
  ('quill_ink', 'Перо и чернильница', 'weapon', 288, '🖋️', 'rare'),
  ('crown_toy', 'Корона из сюрприза', 'hat', 312, '👑', 'rare'),
  ('dagger_ornamental', 'Декоративный кинжал', 'weapon', 398, '🗡️', 'rare'),
  ('cape_short_hero', 'Короткий плащ героя', 'cloak', 336, '🎖️', 'rare'),
  ('blade_runic', 'Клинок с рунами', 'weapon', 720, '⚔️', 'mythical'),
  ('crown_thorns_glow', 'Шипастый венец с мерцанием', 'hat', 860, '👑', 'mythical'),
  ('wings_spectral_half', 'Полупрозрачные крылья', 'wings', 940, '🦅', 'mythical'),
  ('staff_arcane_orb', 'Посох с магической сферой', 'weapon', 1080, '🔮', 'mythical'),
  ('aura_blue_flame', 'Синее пламя вокруг', 'aura', 990, '🔥', 'mythical'),
  ('cloak_starfield', 'Плащ со звёздным небом', 'cloak', 1020, '✨', 'mythical'),
  ('mask_raven', 'Маска ворона', 'mask', 910, '🦉', 'mythical'),
  ('ring_dragon_coil', 'Кольцо змеи дракона', 'ring', 880, '🐉', 'mythical'),
  ('gauntlet_runic_one', 'Руническая перчатка', 'gloves', 790, '🧤', 'mythical'),
  ('amulet_allseeing', 'Амулет всевидящего ока', 'accessory', 1260, '👁️', 'mythical'),
  ('sword_frostmourne_echo', 'Эхо Фростморна', 'weapon', 3200, '❄️', 'legendary'),
  ('crown_lich_king_style', 'Корона в духе Короля-лича', 'hat', 3800, '👑', 'legendary'),
  ('wings_archangel_torn', 'Крылья раненого архангела', 'wings', 4500, '🦅', 'legendary'),
  ('mantle_northwind', 'Мантия северного ветра', 'cloak', 4200, '❄️', 'legendary'),
  ('phoenix_brooch', 'Брошь феникса', 'accessory', 3600, '🔥', 'legendary'),
  ('blade_world_edge', 'Клинок с краю мира', 'weapon', 9800, '⚔️', 'immortal'),
  ('helm_infinity', 'Шлем без начала и конца', 'hat', 11200, '♾️', 'immortal'),
  ('wings_eternal_flame', 'Крылья вечного пламени', 'wings', 14000, '🔥', 'immortal'),
  ('heart_frozen_time', 'Сердце остановившегося времени', 'accessory', 12500, '❤️', 'immortal'),
  ('crown_void_king', 'Корона короля пустоты', 'hat', 15500, '👑', 'immortal')
on conflict (slug) do update set
  name = excluded.name,
  slot = excluded.slot,
  price = excluded.price,
  icon = excluded.icon,
  rarity = excluded.rarity;
